name: terkelola
description: Terkelola Mobile Apps

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  #Base App Needed
  #Technical
  dio: ^4.0.0 #Connection Manager
  http: ^0.13.3 #Base Connection
  flutter_dotenv: ^5.0.0 #For env properties
  pull_to_refresh: ^2.0.0 #Add functionality pull refresh for list
  flutter_secure_storage: ^4.2.0 #For saving session user safely, better than shared preference
  shared_preferences: ^2.0.6 #For saving non secure data
  need_resume: ^1.0.6 #Add lifecycle in Flutter App
  flutter_inappwebview: ^5.3.2 #Webview Android & IOS
  loadmore: ^2.0.1 #Add functionality load more for list
  url_launcher: ^6.0.9 #For launching a URL
  flutter_local_notifications: ^5.0.0+4 #Handle Notification
  encrypt: ^5.0.0 #For Encryption
  provider: ^5.0.0 #State Management

  #UI
  flutter_svg: ^0.22.0 #For render SVG Assets
  introduction_screen: ^2.1.0 #Standar Intro app
  flutter_form_builder: ^6.0.1 #Form Builder
  rflutter_alert: ^2.0.2 #Alert Dialog
  dots_indicator: ^2.0.0 #Dots Indicator for page view
  fluttertoast: ^8.0.7 #Toast
  carousel_slider: ^4.0.0 #Image Carousel
  photo_view: ^0.11.1 #Enlarge Image with zoom function

  #Firebase Dependency
  firebase_crashlytics: ^2.0.7 #Crash Reporting
  firebase_core: ^1.3.0 #Firebase Core Dep
  firebase_core_web: ^1.1.0
  firebase_messaging: ^10.0.3 #Firebase Cloud Messaging Functionality
  firebase_messaging_web: ^2.0.3

  #Social Login
  google_sign_in: ^5.0.4 #Add Google Login
  flutter_facebook_auth: ^3.5.0
  sign_in_with_apple: ^3.0.0 #Add Apple Login

dependency_overrides:
  pointycastle: ^3.2.0-rc0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/certs/
    - assets/images/
    - assets/icons/
    - assets/json/
    - .env

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NunitoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/NunitoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/NunitoSans-BoldItalic.ttf
          weight: 700
          style: italic

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
